name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        If this is not a bug report, please use other relevant channels:

        - [Ask questions on #swapkit-dev channel on Discord](https://discord.com/invite/thorswap)
        - [Propose integrations on #partners-integrations on Discord](https://discord.com/invite/thorswap)

        Before you proceed:

        - Make sure you are on latest versions of SwapKit packages.

  - type: textarea
    attributes:
      label: Current behavior
      description: |
        What code are you running and what is happening? Include a screenshot or video if it's an UI related issue.
      placeholder: Current behavior
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        What do you expect to happen instead?
      placeholder: Expected behavior
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Functionality
      description: |
        What functionality is affected by the issue?
      options:
        - label: Swap
        - label: Liquidity
        - label: Savers
        - label: Loan
        - label: Wallet
        - label: Transactions
        - label: Api
        - label: Other

  - type: checkboxes
    attributes:
      label: Packages
      description: |
        Which packages are affected by the issue?
      options:
        - label: "@lastnetwork/sdk"
        - label: "@lastnetwork/core"
        - label: "@lastnetwork/api"
        - label: "@lastnetwork/helpers"
        - label: "@lastnetwork/tokens"

        - label: "@lastnetwork/toolbox-cosmos"
        - label: "@lastnetwork/toolbox-evm"
        - label: "@lastnetwork/toolbox-utxo"

        - label: "@lastnetwork/wallet-evm-extensions"
        - label: "@lastnetwork/wallet-keepkey"
        - label: "@lastnetwork/wallet-keplr"
        - label: "@lastnetwork/wallet-keystore"
        - label: "@lastnetwork/wallet-ledger"
        - label: "@lastnetwork/wallet-okx"
        - label: "@lastnetwork/wallet-trezor"
        - label: "@lastnetwork/wallet-wc"
        - label: "@lastnetwork/wallet-xdefi"

  - type: textarea
    attributes:
      label: Details
      description: |
        Please provide additional details, if any like screenshots, videos, error stack traces, package versions, etc.
      value: |
        Package versions:
        ```bash
        # Paste the output of `<npm|yarn|pnpm|bun pm> ls --depth=0 | grep @lastnetwork` here
        ```
    validations:
      required: true
